-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 17:30:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pedfaukwzcz0536
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pedfaukwzcz0536
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pedfaukwzcz0536` DEFAULT CHARACTER SET utf8 ;
USE `pedfaukwzcz0536` ;

-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`predmety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`predmety` (
  `idpredmety` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `kod_predmetu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpredmety`),
  UNIQUE INDEX `idpredmety_UNIQUE` (`idpredmety` ASC),
  UNIQUE INDEX `kod_predmetu_UNIQUE` (`kod_predmetu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`bydliste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`bydliste` (
  `idbydliste` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ulice` VARCHAR(50) NOT NULL,
  `cislo_popisne` MEDIUMINT(1) NOT NULL,
  `mesto` VARCHAR(45) NOT NULL,
  `psc` CHAR(6) NOT NULL,
  PRIMARY KEY (`idbydliste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`obor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`obor` (
  `idobor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) NOT NULL,
  `kod_oboru` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idobor`),
  UNIQUE INDEX `idobor_UNIQUE` (`idobor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`druh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`druh` (
  `iddruh` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`iddruh`),
  UNIQUE INDEX `iddruh_UNIQUE` (`iddruh` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`forma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`forma` (
  `idforma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`studium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`studium` (
  `idstudium` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rocnik` TINYINT(6) NOT NULL,
  `obor_idobor` INT UNSIGNED NOT NULL,
  `druh_iddruh` INT UNSIGNED NOT NULL,
  `forma_idforma` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idstudium`, `obor_idobor`, `druh_iddruh`, `forma_idforma`),
  INDEX `fk_studium_obor1_idx` (`obor_idobor` ASC),
  INDEX `fk_studium_druh1_idx` (`druh_iddruh` ASC),
  INDEX `fk_studium_forma1_idx` (`forma_idforma` ASC),
  CONSTRAINT `fk_studium_obor1`
    FOREIGN KEY (`obor_idobor`)
    REFERENCES `pedfaukwzcz0536`.`obor` (`idobor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studium_druh1`
    FOREIGN KEY (`druh_iddruh`)
    REFERENCES `pedfaukwzcz0536`.`druh` (`iddruh`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studium_forma1`
    FOREIGN KEY (`forma_idforma`)
    REFERENCES `pedfaukwzcz0536`.`forma` (`idforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`user` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(20) NOT NULL,
  `prijmeni` VARCHAR(20) NOT NULL,
  `titul` VARCHAR(10) NULL,
  `email` VARCHAR(70) NOT NULL,
  `heslo` VARCHAR(255) NOT NULL,
  `bydliste_idbydliste` INT UNSIGNED NOT NULL,
  `studium_idstudium` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iduser`, `bydliste_idbydliste`, `studium_idstudium`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_bydliste1_idx` (`bydliste_idbydliste` ASC),
  INDEX `fk_user_studium1_idx` (`studium_idstudium` ASC),
  CONSTRAINT `fk_user_bydliste1`
    FOREIGN KEY (`bydliste_idbydliste`)
    REFERENCES `pedfaukwzcz0536`.`bydliste` (`idbydliste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_studium1`
    FOREIGN KEY (`studium_idstudium`)
    REFERENCES `pedfaukwzcz0536`.`studium` (`idstudium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`user_has_predmety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`user_has_predmety` (
  `user_iduser` INT UNSIGNED NOT NULL,
  `predmety_idpredmetu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_iduser`, `predmety_idpredmetu`),
  INDEX `fk_user_has_predmety2_predmety1_idx` (`predmety_idpredmetu` ASC),
  INDEX `fk_user_has_predmety2_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_predmety2_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pedfaukwzcz0536`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_predmety2_predmety1`
    FOREIGN KEY (`predmety_idpredmetu`)
    REFERENCES `pedfaukwzcz0536`.`predmety` (`idpredmetu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`user_has_predmety1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`user_has_predmety1` (
  `user_iduser` INT UNSIGNED NOT NULL,
  `predmety_idpredmetu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_iduser`, `predmety_idpredmetu`),
  INDEX `fk_user_has_predmety1_predmety1_idx` (`predmety_idpredmetu` ASC),
  INDEX `fk_user_has_predmety1_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_predmety1_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pedfaukwzcz0536`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_predmety1_predmety1`
    FOREIGN KEY (`predmety_idpredmetu`)
    REFERENCES `pedfaukwzcz0536`.`predmety` (`idpredmetu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`user_has_predmety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`user_has_predmety` (
  `user_iduser` INT UNSIGNED NOT NULL,
  `predmety_idpredmetu` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_iduser`, `predmety_idpredmetu`),
  INDEX `fk_user_has_predmety2_predmety1_idx` (`predmety_idpredmetu` ASC),
  INDEX `fk_user_has_predmety2_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_predmety2_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pedfaukwzcz0536`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_predmety2_predmety1`
    FOREIGN KEY (`predmety_idpredmetu`)
    REFERENCES `pedfaukwzcz0536`.`predmety` (`idpredmetu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`zapis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`zapis` (
  `idzapis` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kod_predmetu` VARCHAR(12) NOT NULL,
  `nazev_zkousky` VARCHAR(100) NOT NULL,
  `den_vykonani` DATE NOT NULL,
  `klasifikace` VARCHAR(15) NOT NULL,
  `typ_zkousky` VARCHAR(4) NOT NULL,
  `kredit` TINYINT(10) NOT NULL,
  `nazev_skoly` VARCHAR(100) NULL,
  `nazev_fakulty` VARCHAR(100) NOT NULL,
  `dne` DATE NOT NULL,
  `oduvodneni` TEXT(255) NOT NULL,
  PRIMARY KEY (`idzapis`),
  UNIQUE INDEX `idzapis_UNIQUE` (`idzapis` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`obor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`obor` (
  `idobor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(100) NOT NULL,
  `kod_oboru` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idobor`),
  UNIQUE INDEX `idobor_UNIQUE` (`idobor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`predmety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`predmety` (
  `idpredmety` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `kod_predmetu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpredmety`),
  UNIQUE INDEX `idpredmety_UNIQUE` (`idpredmety` ASC),
  UNIQUE INDEX `kod_predmetu_UNIQUE` (`kod_predmetu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`obor_has_predmety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`obor_has_predmety` (
  `obor_idobor` INT UNSIGNED NOT NULL,
  `predmety_idpredmety` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`obor_idobor`, `predmety_idpredmety`),
  INDEX `fk_obor_has_predmety_predmety1_idx` (`predmety_idpredmety` ASC),
  INDEX `fk_obor_has_predmety_obor1_idx` (`obor_idobor` ASC),
  CONSTRAINT `fk_obor_has_predmety_obor1`
    FOREIGN KEY (`obor_idobor`)
    REFERENCES `pedfaukwzcz0536`.`obor` (`idobor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obor_has_predmety_predmety1`
    FOREIGN KEY (`predmety_idpredmety`)
    REFERENCES `pedfaukwzcz0536`.`predmety` (`idpredmety`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`user_has_zapis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`user_has_zapis` (
  `user_iduser` INT UNSIGNED NOT NULL,
  `zapis_idzapis` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_iduser`, `zapis_idzapis`),
  INDEX `fk_user_has_zapis_zapis1_idx` (`zapis_idzapis` ASC),
  INDEX `fk_user_has_zapis_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_zapis_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pedfaukwzcz0536`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_zapis_zapis1`
    FOREIGN KEY (`zapis_idzapis`)
    REFERENCES `pedfaukwzcz0536`.`zapis` (`idzapis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`navstevnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`navstevnik` (
  `idnavstevnik` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(20) NOT NULL,
  `prijmeni` VARCHAR(20) NOT NULL,
  `titul` VARCHAR(10) NULL,
  `email` VARCHAR(70) NOT NULL,
  `obor_studia` VARCHAR(100) NOT NULL,
  `druh_studia` VARCHAR(100) NOT NULL,
  `ulice` VARCHAR(50) NOT NULL,
  `cislo_popisne` MEDIUMINT(1) NOT NULL,
  `mesto` VARCHAR(45) NOT NULL,
  `psc` CHAR(6) NOT NULL,
  `rocnik` TINYINT(6) NOT NULL,
  `forma_studia` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idnavstevnik`),
  UNIQUE INDEX `idnavstevnik_UNIQUE` (`idnavstevnik` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedfaukwzcz0536`.`zapis_has_navstevnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`zapis_has_navstevnik` (
  `zapis_idzapis` INT UNSIGNED NOT NULL,
  `navstevnik_idnavstevnik` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`zapis_idzapis`, `navstevnik_idnavstevnik`),
  INDEX `fk_zapis_has_navstevnik_navstevnik1_idx` (`navstevnik_idnavstevnik` ASC),
  INDEX `fk_zapis_has_navstevnik_zapis1_idx` (`zapis_idzapis` ASC),
  CONSTRAINT `fk_zapis_has_navstevnik_zapis1`
    FOREIGN KEY (`zapis_idzapis`)
    REFERENCES `pedfaukwzcz0536`.`zapis` (`idzapis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zapis_has_navstevnik_navstevnik1`
    FOREIGN KEY (`navstevnik_idnavstevnik`)
    REFERENCES `pedfaukwzcz0536`.`navstevnik` (`idnavstevnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pedfaukwzcz0536` ;

-- -----------------------------------------------------
-- Placeholder table for view `pedfaukwzcz0536`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedfaukwzcz0536`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `pedfaukwzcz0536`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedfaukwzcz0536`.`view1`;
USE `pedfaukwzcz0536`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
