INSERT INTO obor(nazev, kod_oboru) VALUES  
('Speciální pedagogika','OBSP08'),
('Společný základ pro obory se zaměřením na vzdělávání a pedagogiku','OBUZ17'),
('Anglický jazyk se zaměřením na vzdělávání','OB2AJ10'),
('Anglický jazyk se zaměřením na vzdělávání','OB2AJ17'),
('Biologie, geologie a environmentalistika se zaměřením na vzdělávání','OB2BI06'),
('Biologie, geologie a environmentalistika se zaměřením na vzdělávání','OB2BI17'),
('Český jazyk se zaměřením na vzdělávání','OB2CJ08'),
('Český jazyk se zaměřením na vzdělávání','OB2CJ09'),
('Chemie se zaměřením na vzdělávání','OB2CH17'),
('Dějepis se zaměřením na vzdělávání','OB2DJ06'),
('Dějepis se zaměřením na vzdělávání','OB2DJ17'),
('Francouzský jazyk se zaměřením na vzdělávání','OB2FJ06'),
('Francouzský jazyk se zaměřením na vzdělávání','OB2FJ17'),
('Hra na nástroj se zaměřením na vzdělávání','OB2NA06'),
('Hra na nástroj se zaměřením na vzdělávání','OB2NA10'),
('Hudební výchova se zaměřením na vzdělávání','OB2HV06'),
('Informační technologie se zaměřením na vzdělávání','OB2IT12'),
('Informační technologie se zaměřením na vzdělávání','OB1IT13'),
('Informační technologie se zaměřením na vzdělávání','OB2IT17'),
('Informační technologie se zaměřením na vzdělávání','OB1IT17'),
('Matematika se zaměřením na vzdělávání','OB2MA06'),
('Matematika se zaměřením na vzdělávání','OB2MA10'),
('Matematika se zaměřením na vzdělávání','OB2MA17'),
('Matematika se zaměřením na vzdělávání','OB1MA17'),
('Německý jazyk se zaměřením na vzdělávání','OB2NJ17'),
('Pedagogika','OB2PG06'),
('Pedagogika','OB2PG17'),
('Ruský jazyk se zaměřením na vzdělávání','OB2RL06'),
('Ruský jazyk se zaměřením na vzdělávání','OB2RL17'),
('Sbormistrovství chrámové hudby','OBSBCH'),
('Sbormistrovství se zaměřením na vzdělávání','OB2SB06'),
('Sbormistrovství se zaměřením na vzdělávání','OB2SB17'),
('Speciální pedagogika se zaměřením na vzdělávání','OB2SP07'),
('Speciální pedagogika se zaměřením na vzdělávání','OB2SP17'),
('Technická a informační výchova se zaměřením na vzdělávání','OB2TI06'),
('Technická a informační výchova se zaměřením na vzdělávání','OB2TI10'),
('Tělesná výchova a sport se zaměřením na vzdělávání','OB2TV06'),
('Tělesná výchova a sport se zaměřením na vzdělávání','OB2TV17'),
('Učitelství pro mateřské školy','OBMSDV08'),
('Učitelství pro mateřské školy','OBMSTV08'),
('Učitelství pro mateřské školy','OBMSHV17'),
('Učitelství pro mateřské školy','OBMSVV17'),
('Výchova ke zdraví se zaměřením na vzdělávání','OB2VZ08'),
('Výchova ke zdraví se zaměřením na vzdělávání','OB2VZ17'),
('Výtvarná výchova se zaměřením na vzdělávání','OB2VV17'),
('Výtvarná výchova se zaměřením na vzdělávání','OB1VV17'),
('Základy společenských věd se zaměřením na vzdělávání','OB2SV06'),
('Choir Conducting Oriented at Education','OEB2SB10'),
('English Language Oriented at Education','OEB2AJ10'),
('Music Oriented at Education','OEB2HV10'),
('Musical Instrument Oriented at Education','OEB2NA10');

INSERT INTO predmety(nazev, kod_predmetu) VALUES 
('Arteterapie I.','OBSTE8811'),
('Ergoterapie I.','OBEP18R13'),
('Muzikoterapie I.','OBSP18312'),
('Alternativní a augmentativní komunikace','OBSX18511'),
('Základy školského managmentu','OBXP18402'),
('Základy sociálního managmentu','OBSP18401'),
('Romský jazyk','OBSP18513'),
('Základy znakového jazyka','OBSP18512'),
('Tvorba individuálně vzdělávacích plánů','OBSD18290'),
('Podpora samostatnosti a nezávislosti','OBSP1F260'),
('Cizí jazyk – angličtina','OPBZ0A11SC'),
('Cizí jazyk – němčina','OPBZ0G114C'),
('Cizí jazyk odborný – angličtina','OPBZ0F117C'),
('Cizí jazyk odborný – němčina','OPBZ0GG18C'),
('Academic English','OPBZ0A115C'),
('International Certificates in Practical Use','OPBZ0AA16C'),
('Grafika na počítači','OPBZ0I120C'),
('Tvorba webových stránek','OPBZ0I121C'),
('Zpracování dat v cloudu','OPBZ0I122C'),
('Předlékařská první pomoc','OPAZ0P126C'),
('Vývojová biologie dítěte','OPBZ0B125C'),
('Úvod do politologie','OPBZ0O128C'),
('Úvod do filozofie','OPBZ0O130C'),
('Literatura s tématikou dětství I','OB2301A24'),
('British Studies','OB2301022'),
('Psaní I','OB2301023'),
('American Studies','OB2301025'),
('Literatura s tématikou dětství II','OB23A1027'),
('Překlad I','OB2301129'),
('Tvůrčí psaní','OB2301035'),
('Aj v multikulturní Evropě I','OB2301A34'),
('Sborová praxe I','OB2308122'),
('Orchestrální praxe I','OB2308123'),
('Veřejné vystoupení v nástrojové praxi','OB230A131'),
('Sbormistrovské praktikum','OB2308136'),
('Dirigentské praktikum','OB2308137'),
('Umělecká a vědecká prezentace','OB2308146'),
('Komorní sbor','OB2308147'),
('Dramatická výchova','OB2308178'),
('Pravoslavná hudba','OB23R8180'),
('Hudební fyziologie a fyzioterapie','OBA308188'),
('Hudební fyziologie a fyzioterapie','OB2308181'),
('Pravoslavná hudba','OB2308180'),
('Etnická hudba a etnomuzikologie','OBA308179'),
('Dramatická výchova','OB2E08178'),
('Hra a doprovod písní na klavír','OB2308173'),
('Smíšený sbor','OB2308171'),
('Umělecká a vědecká prezentace','OB230A146'),
('Sbormistrovské praktikum','OB2308A36'),
('Chemické výpočty','OB2309032'),
('Struktura v názvech chemických sloučenin','OB230A033'),
('Angličtina pro studenty přírodovědných předmětů','OB2309D34'),
('Chemistry Informatics','OEB23R9025'),
('Instrumentální metody','OB2309R28'),
('Laboratoř fyzikální chemie','OB23E9027'),
('Biochemie','OB2309R11'),
('Základy chemických výrob','OB230E031');
